pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

rootProject.name = 'GoNative'
System.setProperty("user.dir", rootProject.projectDir.toString())

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://maven.median.co' }
        maven { url "$rootDir/maven" }
    }
}

apply from: file("./plugins.gradle"); applyModulesSettingsGradle(settings)
include ':app'
